### ISSUE TITLE
Broken link on the homepage: Palm apps

### ISSUE THREAD

**Issue by danielcgold** [remy/remysharp.com#10]
The link found in https://github.com/remy/remysharp.com/blob/99fa60a338819e0cdefd1438fcde244e639e124e/public/index.jade#L48 is broken.

**Comment by remy** [comment]
Ta. That's a bigger problem - one of my servers appears to have dropped out of the loop!!!

Will fix/resurrect!

**Comment by remy** [comment]
…apparently 4 years is how long I need to close this issue now that a) I've resurrected the site and b) don't include the link.

lol - and thank you for the original issue :-D
