### ISSUE TITLE
RSS feed error

### ISSUE THREAD

**Issue by iambacon** [remy/remysharp.com#30]
Sorry Remy me again.

Clicking on the feed link in Chrome (55.0.2883.87) and Opera results in the following error

> error on line 7 at column 40: Opening and ending tag mismatch: link line 0 and head

![image](https://cloud.githubusercontent.com/assets/2139123/21307049/c18c46f6-c5cb-11e6-8b88-6b8cdd6a41a6.png)

**Comment by remy** [comment]
Damnit. This is an opera thing too. I'll have to find where there's a
relative image link. Will fix today, ta for reporting.

**Comment by remy** [comment]
Actually, this isn't opera at all (I thought it was related), but it's my whole feed is injecting HTML when it shouldn't be. Trying to fix.

**Comment by remy** [comment]
Fixed and live. Thanks again.
