### ISSUE TITLE
GUI app to sort FAT drives

### ISSUE THREAD

**Issue by lwouis** [remy/remysharp.com#74]
Hi,

I wrote a native macOS app to sort FAT drives. It has a UI, so easier to use, and it's free and open-source.

You can find it here: https://fat-drive-sorter.netlify.app/

I'm sharing this with you because when I first Google'd for a solution, [your post](https://github.com/remy/remysharp.com/blob/main/public/til/cli/sorting-fat32-sdcard.md) came up.

I hope it helps 👍

**Comment by remy** [comment]
Nice (and I somehow won the google seo foo!). I'll add this to the post because it's genuinely useful 👍
