### ISSUE TITLE
Incorrect <pubDate> in feed.xml causing issue in Feedbro

### ISSUE THREAD

**Issue by simevidas** [remy/remysharp.com#75]
There is a problem with this line of code:

```pug
pubDate= moment(post.data.date).format('ddd, dd MMM yyyy HH:mm:ss +0000')
```

https://github.com/remy/remysharp.com/blob/main/public/feed.xml.pug#L41

This is generating XML code like this:

```xml
<pubDate>026, 26 Mar 2023 22:43:38 +0000</pubDate>
```

This is an invalid value:

https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fremysharp.com%2Ffeed.xml

As a result, in the Feedbro feed reader, the same feed items are being repeatedly marked as new over and over again because Feedbro ignores the invalid date values.

**Comment by remy** [comment]
Cheers. I'll sort that today. I bumped all my libraries and obviously date-fns (which moment is actually aliased to) completely changed their formats!

**Comment by remy** [comment]
That's going live now - thanks again chap
